apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  dataFrom:
    - extract:
        key: {{ .Values.externalSecretRemoteRefKey }}
  target:
    name: controller-manager