apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  dataFrom:
    - extract:
        key: tailscale-{{ .Values.cluster_name }}
  target:
    name: tailscale-subnet-router-secrets